export enum ZDevicePin {
  DOOR_SENSOR = 'DOOR_SENSOR',
  MOTION_SENSOR = 'MOTION_SENSOR',
  TEMPERATURE_SENSOR = 'TEMPERATURE_SENSOR',
  HUMIDITY_SENSOR = 'HUMIDITY_SENSOR',
  TEMP_HUMI_SENSOR = 'TEMP_HUMI_SENSOR',
  LIGHT_SENSOR = 'LIGHT_SENSOR',
  SMOKE_SENSOR = 'SMOKE_SENSOR',

  SWITCH_1G = 'SWITCH_1G',
  SWITCH_2G = 'SWITCH_2G',
  SWITCH_3G = 'SWITCH_3G',

  SOCKET_1G = 'SOCKET_1G',
  SOCKET_2G = 'SOCKET_2G',
  SOCKET_3G = 'SOCKET_3G',

  DIMMER_1G = 'DIMMER_1G',
  DIMMER_2G = 'DIMMER_2G',
}
