export enum ZDevicePin {
  DOOR_SENSOR = 'DOOR_SENSOR',
  MOTION_SENSOR = 'MOTION_SENSOR',
  TH_SENSOR = 'TH_SENSOR',

  SWITCH_1G = 'SWITCH_1G',
  SWITCH_2G = 'SWITCH_2G',
  SWITCH_3G = 'SWITCH_3G',
}
